backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "الصفحات"
    files:
      - label: "الصفحة الرئيسية"
        name: "home"
        file: "index.html"
        fields:
          - {label: "العنوان", name: "title", widget: "string"}
          - {label: "المحتوى", name: "body", widget: "markdown"}
